WebApplicationASPNETCore3/Controllers/CampaignController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

using CRM.Models.Entities;
using CRM.Models.ViewModels;
using CRM.Services;
using CRM.Services.ViewModels;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Storage;

namespace CRM.Controllers
{
	//[EZAuth(permissions: "Agent")]
	public class CampaignController : Controller
    {
        private readonly CRMContext _context;
        private readonly CampaignService _campaignService;
        private readonly EZAuth _ezAuth;
        private readonly EZSession _ezSession;

        public CampaignController(EZAuth ezAuth, EZSession ezSession, CRMContext context, CampaignService campaignService)
        {
            _context = context;
            _campaignService = campaignService;
            _ezAuth = ezAuth;
            _ezSession = ezSession;
        }
        public async Task<IActionResult> Index()
        {
            int _currentPage = 1;
            int _pageSize = 10;
            CampaignPagination campaignPagination = await _campaignService.GetPaginatedResult(null, _currentPage, _pageSize);

            return View(campaignPagination);
        }
        public async Task<IActionResult> LoadCampaignList(int? currentPage, int? pageSize, string searchText )
        {
            int _currentPage = currentPage == null ? 1 : currentPage.GetValueOrDefault();
            int _pageSize = pageSize == null ? 10 : pageSize.GetValueOrDefault();
           
            CampaignPagination campaignPagination = await _campaignService.GetPaginatedResult(searchText, _currentPage, _pageSize);

            return PartialView("_CampaignListPartial",campaignPagination);
        }
        

        public ActionResult GetCampaignList()
        {
            var campaigns = _context.Campaign.Select(x => new
            {
                Id = x.Id,
                Name = x.Name,

            })
            .ToList();
            return Ok(campaigns);
        }

       [HttpPost]
        public async Task<IActionResult> ChangeWKCampaign(int wkCampaignId)
        {
            var campaign = await _campaignService.GetCampaignById(wkCampaignId);
            if (campaign == null)
                return BadRequest();

            _ezSession.wkCampaignId = campaign.Id.ToString();
            _ezSession.wKCampaignName = campaign.Name.ToString();
            //_httpContext.Session.Set("wKCampaignId", Encoding.UTF8.GetBytes(campaign.Id.ToString()));
            //_httpContext.Session.Set("wKCampaignName", Encoding.UTF8.GetBytes(campaign.Name));
            //TempData["WKCampaignId"] = campaign.Id;
            //TempData["WKCampaignName"] = campaign.Name;
            //TempData.Keep();
            //RedirectToAction("Home", "Index", new { returnUrl = "" });
            return Ok();
        }

        public ActionResult Create(string tabId)
        {
            ViewBag.tabId = String.IsNullOrEmpty(tabId) ? "0" : tabId;
            ViewData["Title"] = "Campaign: "; 
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Campaign model)
        {
            Campaign campaign = null;
            if (ModelState.IsValid)
            {
                campaign = await _campaignService.Create(_ezAuth.UserName, model);

            }

            //Pass to the tab details view
            if (campaign != null)
            {
                ViewBag.CampaignId = campaign.Id;
                ViewBag.CampaignName = campaign.Name;
                ViewData["Title"] = "Campaign: " + campaign.Name;
            }

            return View(model);
        }

        public async Task<IActionResult> Edit(int? id, string tabId)
        {
            ViewBag.tabId = String.IsNullOrEmpty(tabId) ? "0" : tabId;
           

            if (id == null )
            {
                return  BadRequest("Bad request campaign Id");
            }

           

            Campaign campaign = await _campaignService.GetCampaignById(id.GetValueOrDefault());
            if (campaign == null)
            {
                return NotFound();
            }

            //Pass to the tab details view
            ViewBag.CampaignId = id;
            ViewBag.CampaignName = campaign.Name;
            ViewData["Title"] = "Campaign: " + campaign.Name;

            return View(campaign);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id, Campaign model)
        {
            Campaign campaignToUpdate = null;
            if (id == null)
            {
                return  BadRequest("Bad request campaign Id");
            }
            if (ModelState.IsValid)
            {
                campaignToUpdate = await _campaignService.Update(_ezAuth.UserName, id.GetValueOrDefault(), model);
            
            }
            //Pass to the tab details view
            ViewBag.CampaignId = model.Id;
            ViewBag.CampaignName = model.Name;
            ViewData["Title"] = "Campaign: " + model.Name;

            return View(model);
        }

    }
}

WebApplicationASPNETCore3/Controllers/PackageController.cs
using System;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

using CRM.Models.Entities;
using CRM.Models.ViewModels;
using CRM.Services;
using CRM.Services.ViewModels;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Storage;


namespace CRM.Controllers
{
    //[EZAuth(permissions: "Agent")]
    public class PackageController : Controller
    {
        private readonly CRMContext _context;
        private readonly PackageService _packageService;
        private readonly CampaignService _campaignService;
        private readonly EZAuth _ezAuth;
        private readonly EZSession _ezSession;

        public PackageController(EZAuth ezAuth, EZSession ezSession, CRMContext context, PackageService packageService, CampaignService campaignService)
        {
            _context = context;
            _packageService = packageService;
            _campaignService = campaignService;
            _ezAuth = ezAuth;
            _ezSession = ezSession;
        }

        public async Task<IActionResult> Index(bool hasError, string tabId, int campaignId, string campaignName)
        {
            ViewBag.tabId = String.IsNullOrEmpty(tabId) ? "0" : tabId;
            ViewBag.CampaignId = campaignId;
            ViewBag.CampaignName = campaignName;
            ViewData["Title"] = "Campaign: " + campaignName;

            List<Package> packages = await _packageService.GetPackageByCampaignId(campaignId);

            return View(packages);
        }



        public ActionResult Create(string tabId)
        {
            ViewBag.tabId = String.IsNullOrEmpty(tabId) ? "0" : tabId;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Package model)
        {
            if (ModelState.IsValid)
            {
                Package Package = await _packageService.Create(_ezAuth.UserName, model);

            }
            else
            {
                //TODO: return error save
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int? id, string tabId)
        {
            ViewBag.tabId = String.IsNullOrEmpty(tabId) ? "0" : tabId;

            if (id == null)
            {
                return BadRequest("Bad request Package Id");
            }
            Package Package = await _packageService.GetPackageById(id.GetValueOrDefault());
            if (Package == null)
            {
                return NotFound();
            }
            return View(Package);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id, Package model)
        {
            Package PackageToUpdate = null;
            if (id == null)
            {
                return BadRequest("Bad request Package Id");
            }
            if (ModelState.IsValid)
            {
                PackageToUpdate = await _packageService.Update(_ezAuth.UserName, id.GetValueOrDefault(), model);

            }

            return View(model);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest("Bad request Package Id");
            }
            
            await _packageService.Delete(_ezAuth.UserName, id.GetValueOrDefault());

            return Ok();
        }
        public async Task<IActionResult> LoadPackageList(int? campaignId)
        {

            if (campaignId == null)
            {
                return BadRequest("Could not load due to bad input campaign.");
            }

            List<Package> packages = await _packageService.GetPackageByCampaignId(campaignId.GetValueOrDefault());

            return PartialView("_PackageListPartial", packages);
        }

        public async Task<IActionResult> PackageNewEditModalPage(int? id, int campaignId)
        {
            Package package = null;
            if (id == null)
            {
                return BadRequest("Bad request Package Id");
            }
            if (id > 0)
                package = await _packageService.GetPackageById(id.GetValueOrDefault());
            else
            {
                package = new Package();
                package.Status = ItemStatus.A;  //pre-select Status 
            }
            //package.CampaignId = campaignId; //TODO: verify this is not null
            //if (package == null)
            //{
            //    return NotFound();
            //}

            return PartialView("_PackageDetailModalPartial", package);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ProcessPackageModalPage(Package model)
        {

            Package PackageToUpdate = null;
            if (model == null)
            {
                return BadRequest("Bad request Package Form");
            }
            if (ModelState.IsValid)
            {
                if (model.Id > 0)
                {
                    PackageToUpdate = await _packageService.Update(_ezAuth.UserName, model.Id, model);
                    if (PackageToUpdate == null)
                        return NotFound("No Record updated.");
                }
                else //Id=0
                {
                    PackageToUpdate = await _packageService.Create(_ezAuth.UserName, model);

                }
            }



            return Ok();
        }

        public async Task<IActionResult> PackageCopyModalPage(int? campaignId)
        {
            List<Campaign> campaigns = null;
            if (campaignId == null)
            {
                return BadRequest("Bad request Package Id");
            }
            if (campaignId > 0)  
            {
                campaigns = await _campaignService.GetCampaign();
                ViewBag.CampaignList = campaigns.Where(m=> m.Id != campaignId ).Select(m => new SelectListItem { Text = m.Name, Value = m.Id.ToString() }).ToList();
                //select only all except target Campaign Id
            }

            return PartialView("_PackageCopyModalPartial");
        }

        public async Task<string> PackageCopyModalPageGetPackages(int? id)
        {
           
            int campaignId = id.GetValueOrDefault(); //source campaign Id
            List<Package> packages = await _packageService.GetPackageByCampaignId(campaignId);
            List<SelectListItem> packageList = packages.Select(m => new SelectListItem { Text = m.Name, Value = m.Id.ToString() }).ToList();
            
            return JsonSerializer.Serialize(packageList); ;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ProcessCopyPackageModalPage(int? campaignId, int? sc, string[] sp)
        {
           
            if (campaignId == null )
            {
                return BadRequest("Bad Request Campaign Id in Package Form");
            }

            if (sp == null || sc == null)
            {
                return BadRequest("No Selection source Package in Package Form");
            }

            List<Package> packages = await _packageService.CopyMultiPackages(_ezAuth.UserName,  campaignId,  sc,  sp);
            if (packages.Count == 0)
                return NotFound("Nothing to be copied."); //TODO: replace with no create status
            return Ok();
        }
    }

}

WebApplicationASPNETCore3/Controllers/TestSideBarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CRM.Models;
using CRM.Services;

   

namespace CRM.Controllers
{
    public class TestSideBarController : Controller
    {
        private readonly ILogger<TestSideBarController> _logger;
        private readonly EZAuth _ezAuth;

        public TestSideBarController(EZAuth ezAuth, ILogger<TestSideBarController> logger)
        {
            _logger = logger;
            _ezAuth = ezAuth;
        }

        public IActionResult Index()
        {
            ViewBag.DD = "{\"1\": \"Black Widow\", \"2\": \"Captain America\", \"3\": \"Iron Man\"}";

            return View();
        }
        public IActionResult Index1()
        {

            return View();
        }
    }
}

WebApplicationASPNETCore3/Views/Shared/_CampaignLeftBarMenuPartial.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item"><a class="nav-link text-black" asp-area="" asp-controller="Campaign" asp-action="Index">Listing</a></li>
    <li class="nav-item"><a class="nav-link text-black" asp-area="" asp-controller="Campaign" asp-action="Create">Create New</a></li>

</ul>

WebApplicationASPNETCore3/Views/Shared/_CampaignTabsPartial.cshtml
@{
    var tabId = ViewBag.tabId == null ? "0": ViewBag.tabId;
    var campaignId = ViewBag.CampaignId == null ? "0": ViewBag.CampaignId.ToString();
    var campaignName = ViewBag.CampaignName == null ? "??": ViewBag.campaignName;

   
}
    <br />
    <h4>Campaign - @campaignName</h4>
    <br />
    <ul class="nav nav-pills  nav-fill">
        <li class="nav-item">
            @*@Html.ActionLink("Detail", "Edit", "Campaign", new { id = campaignId }, new { @class = "nav-link (tabId =='0' ?'active'':'' "})*@
            @*<a class="nav-link @(tabId =="0" ?"active":"") " asp-controller="Campaign" asp-action="Edit" asp-route-tabId="0" asp-route-campaignId="@campaignId">Details</a>*@
            <a onclick="return CheckTab(0,'@campaignId');" class="nav-link @(tabId =="0" ?"active":"") " href="/Campaign/Edit/@campaignId">Details</a>
        </li>
        <li class="nav-item">
            <a onclick="return CheckTab(1,'@campaignId');" class="nav-link @(tabId =="1"  ?"active":"")" asp-controller="Package" asp-action="Index" asp-route-tabId="1"  asp-route-campaignId="@campaignId" asp-route-campaignName="@campaignName">Packages</a>
        </li>
        <li class="nav-item">
            <a onclick="return CheckTab(2,'@campaignId');" class="nav-link @(tabId =="2"  ?"active":"") " asp-controller="Status" asp-action="Index" asp-route-tabId="2" asp-route-campaignId="@campaignId" asp-route-campaignName="@campaignName">Status Codes</a>
        </li>
        <li class="nav-item">
            <a onclick="return CheckTab(3,'@campaignId');" class="nav-link @(tabId =="3"  ?"active":"") " asp-controller="CustomerFileUpload" asp-action="Index" asp-route-tabId="3" asp-route-campaignId="@campaignId" asp-route-campaignName="@campaignName">Customer File Upload</a>
        </li>
        <li class="nav-item">
            <a onclick="return CheckTab(4,'@campaignId');" class="nav-link @(tabId =="4"  ?"active":"") " asp-controller="TeamDistribution" asp-action="Index" asp-route-tabId="4" asp-route-campaignId="@campaignId" asp-route-campaignName="@campaignName">Team Distribution</a>
        </li>
    </ul>
<input type="hidden" value="@campaignId" id="hidCampaignId" />
    <br />

<script type="text/javascript">
    
    function CheckTab(tabId, campaignId)
    {
        //validate campaignId ==0 before move to another tab
        if (campaignId == "0" && tabId > 0)
        {
            alert('Please save campaign details first.');
            return false;
        }
    }
</script>

WebApplicationASPNETCore3/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc
@using System.Text
@inject CRM.Services.EZAuth AuthService
@inject CRM.Services.EZSession SessionService
@{
    var authInfo = AuthService;
    var sessionService = SessionService;
   
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CRM - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet">

    @*<link rel="stylesheet" href="~/lib/bootstrap-multiselect/dist/css/bootstrap-multiselect.css" />*@
    @*<link rel="stylesheet" href="~/lib/bootstrap4-multiselect/dist/css/BsMultiSelect.css" />*@
    @*<link rel="stylesheet" href="~/lib/Checkbox-Radio-Inputs-To-Dropdown-jQuery/input-to-dropdown.css" />*@


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @*<script src="~/lib/bootstrap-multiselect/dist/js/bootstrap-multiselect.js"></script>*@
    @*<script src="~/lib/bootstrap4-multiselect/dist/js/BsMultiSelect.js"></script>*@
    @*<script src="~/lib/Checkbox-Radio-Inputs-To-Dropdown-jQuery/input-to-dropdown.js"></script>*@



    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container" style="max-width: 100%; margin: 0;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRM</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    @if (authInfo.IsAuthenticated)
                    {
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="Campaign" asp-action="Index">Campaign</a></li>
                        @*<li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="UserManagement" asp-action="Index">User Management</a></li>*@
                        @if (authInfo.IsInRole("Admin"))
                        {<li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Index">User</a></li>}
                        <li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a></li>
                        <li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="TestSideBar" asp-action="Index">TestSideBar</a></li>
                    </ul>
                        <ul class="navbar-nav navbar-right">

                            @*<li class="nav-item dropdown nav-user-menu">
                                    <a href="javascript:void(0);" class="nav-link" data-toggle="dropdown" role="button">
                                        <img class="user-image img-circle elevation-2" src="~/libs/admin-lte/dist/img/avatar5.png" alt="User Image">
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" asp-controller="Users" asp-action="ChangePassword">
                                            <i class="fas fa-user-edit"></i>UpdatePassword
                                        </a>
                                        <a class="dropdown-item" asp-controller="Account" asp-action="Logout">
                                            <i class="fas fa-sign-out-alt"></i> Logout
                                        </a>
                                    </div>
                                </li>*@
                            
                                <li class="nav-item">
                                    <a class="nav-link text-white" href="javascript:void(0);" data-toggle="dropdown" role="button">
                                        <i class="fa fa-user-circle" aria-hidden="true"></i>
                                        @authInfo.UserName
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" style="padding:5px">
                                        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="form-inline">

                                            <button type="submit" class="btn btn-link navbar-btn navbar-link bg-white">Log out</button>
                                        </form>
                                    </div>
                                </li>

                            </ul>
                        }
                        else
                        {

                            <ul class="navbar-nav navbar-right list-inline ml-auto">
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">Log in</a>
                                </li>
                            </ul>
                        }
                    </div>
                </div>
            </nav>
        </header>
        @*<div class="container">*@
                                @*<main role="main">*@
                                @RenderBody()
                                @*</main>*@
                                @*</div>*@
                                @*<div id="PopoverContent" class="d-none">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Recipient's username"
                       aria-label="Recipient's username with two button addons" aria-describedby="button-addon1">
                <div class="input-group-append" id="button-addon1">
                    <button class="btn btn-outline-primary" t++ype="button" data-toggle="popover" data-placement="bottom"
                            data-html="true" data-title="Search">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>*@

        <footer class="border-top footer text-muted">
            <div class="container">
                Copyright © 2020 CRM. All Rights Reserved
            </div>
        </footer>

</body>
</html>

WebApplicationASPNETCore3/Views/Shared/_UserLeftBarMenuPartial.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item"><a class="nav-link text-black" asp-area="" asp-controller="User" asp-action="Index">Listing</a></li>
    <li class="nav-item"><a class="nav-link text-black"  href="#" onclick="userNew();" >Create New</a></li>

</ul>

WebApplicationASPNETCore3/Views/Shared/_curCampaignPartial.cshtml
@using Microsoft.AspNetCore.Http
@model CRM.Models.ViewModels.AccountLogin

<label>Campaign1
    @*@HttpContext.Session.GetString("currentCampaign")*@

</label>